# identity_type for now is only 'Ephemeral'
# someday we will support a 'Supplied' type
identity_type = 'Ephemeral'

# list all the network interfaces you want to bind to
# note for now only the first is used
# (but you can specify '0.0.0.0')
[[binding_endpoints]]
addr = '0.0.0.0'
port = 8080

# list all the bootstrap nodes you want to try connecting to
[[bootstrap_endpoints]]
addr = '127.0.0.1'
port = 8081
