[package]
name = "lib3h"
version = "0.1.0"
authors = ["neonphog <neonphog@gmail.com>"]

[dependencies]
error-chain = "0.12"
libsodacon = { path = "../libsodacon" }
serde = "1.0"
serde_derive = "1.0"
rmp-serde = "0.13.7"
