[package]
name = "holochain_lib3h"
version = "0.0.1-alpha1"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
holochain_logging = { path = "../logging" }
holochain_lib3h_protocol = { path = "../lib3h_protocol" }
holochain_sodium = { path = "../sodium" }
