version: 2

jobs:
 # must be called build for local circle cli to work
 # is actually unit tests
 build:
  docker:
   - image: holochain/holochain-rust:latest
  resource_class: large
  working_directory: ~/repo
  steps:
   - checkout
   - run: make test
