version: 2

jobs:
 # must be called build for local circle cli to work
 # is actually unit tests
 build:
  docker:
   - image: holochain/holochain-rust:latest
  resource_class: large
  working_directory: ~/repo
  steps:
   - checkout
   - run: nix-shell -p git --run 'git clone https://github.com/holochain/holochain-rust.git'
   - run: nix-shell holochain-rust/default.nix --run 'cargo install rustfmt-nightly --vers 1.0.1'
   - run: nix-shell holochain-rust/default.nix --run 'make test'
